name: proyecto_final_grupo_6
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  badges: ^3.1.2
  cloud_firestore: ^4.17.3
  firebase_core: ^2.31.1
  firebase_storage: ^11.7.7
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  go_router: ^14.0.2
  image_picker: ^1.1.1

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
