// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDz3lWgXVOs8gvIFRFgWxZcWYS3PEZ2cXk',
    appId: '1:998191787388:web:a37f33e5f30f83870748f9',
    messagingSenderId: '998191787388',
    projectId: 'belligrau-e8c3a',
    authDomain: 'belligrau-e8c3a.firebaseapp.com',
    storageBucket: 'belligrau-e8c3a.appspot.com',
    measurementId: 'G-FV4D2HLJE3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACGGds7gURgya_u8GMOxispFaTwJTt7lE',
    appId: '1:998191787388:android:0c0d05bea4d2e6ab0748f9',
    messagingSenderId: '998191787388',
    projectId: 'belligrau-e8c3a',
    storageBucket: 'belligrau-e8c3a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDl03os7w66v2FVHODlv5Z9T-jUwOkQYPM',
    appId: '1:998191787388:ios:01721185cad24c010748f9',
    messagingSenderId: '998191787388',
    projectId: 'belligrau-e8c3a',
    storageBucket: 'belligrau-e8c3a.appspot.com',
    iosBundleId: 'com.example.proyectoFinalGrupo6',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDl03os7w66v2FVHODlv5Z9T-jUwOkQYPM',
    appId: '1:998191787388:ios:01721185cad24c010748f9',
    messagingSenderId: '998191787388',
    projectId: 'belligrau-e8c3a',
    storageBucket: 'belligrau-e8c3a.appspot.com',
    iosBundleId: 'com.example.proyectoFinalGrupo6',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDz3lWgXVOs8gvIFRFgWxZcWYS3PEZ2cXk',
    appId: '1:998191787388:web:98bb88e8c88270a00748f9',
    messagingSenderId: '998191787388',
    projectId: 'belligrau-e8c3a',
    authDomain: 'belligrau-e8c3a.firebaseapp.com',
    storageBucket: 'belligrau-e8c3a.appspot.com',
    measurementId: 'G-06FCZW92BV',
  );
}
